title: Wonyoung Blog
author: Wonyoung
email: wonyoung0105@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  초보 개발자가 소소하게 공부한거 올리는 공간.
  가끔 심심하면 사진찍은것도 올려볼까 합니다.
show_excerpts: false # set to true to show excerpts on the homepage
baseurl: 

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Wonyoung yoo
  tagline: 초보 Software Engineer
  disqus_shortname: wonyoung
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    github:  yoowonyoung
    linkedIn: in/원영-유-2b2147121/
    instagram: dnjsdud0105
 
paginate: 10

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  #- jekyll-feed
